<?php

namespace Iut\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipateRepository extends EntityRepository
{
}
